apiVersion: batch/v1
kind: Job
metadata:
  name: nova-post
spec:
  template:
    metadata:
      annotations:
{{ include "init-containers-header" . }}
{{ include "init-containers-footer" .Values.dependencies.post }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: nova-post
          image: {{ .Values.image.post }}
          imagePullPolicy: Always
          command:
            - bash
            - /tmp/post.sh
          env:
            - name: ANSIBLE_LIBRARY
              value: /usr/share/ansible/
          volumeMounts:
            - name: novaconf
              mountPath: /etc/nova/nova.conf
              subPath: nova.conf
            - name: nova-bin
              mountPath: /tmp/post.sh
              subPath: post.sh
      volumes:
        - name: novaconf
          configMap:
            name: nova-etc
        - name: nova-bin
          configMap:
            name: nova-bin
