apiVersion: batch/v1
kind: Job
metadata:
  name: nova-db-sync
spec:
  template:
    metadata:
      annotations:
{{ include "init-containers-header" . }}
{{ include "init-containers-footer" .Values.dependencies.db_sync }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: nova-db-sync
          image: {{ .Values.image.db_sync }}
          imagePullPolicy: Always
          command:
            - bash
            - /tmp/db-sync.sh
          volumeMounts:
            - name: novaconf
              mountPath: /etc/nova/nova.conf
              subPath: nova.conf
            - name: nova-bin
              mountPath: /tmp/db-sync.sh
              subPath: db-sync.sh
      volumes:
        - name: novaconf
          configMap:
            name: nova-etc
        - name: nova-bin
          configMap:
            name: nova-bin
