# Default values for utils.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  region: cluster
  tld: local

  control_replicas: 1
  compute_replicas: 1
  labels:
    control_node_selector_key: openstack-control-plane
    control_node_selector_value: enabled
    compute_node_selector_key: openstack-compute-node
    compute_node_selector_value: enabled

  network:
    ip_address: "0.0.0.0"
    external_ips: ""
    minion_interface_name: "eno1"
    dns:
      servers:
        - "10.3.0.10"

  database:
    address: "mariadb"
    port: 3306
    root_user: "root"
    root_password: "password"

  keystone:
    auth_uri: "http://keystone-api:5000"
    auth_url: "http://keystone-api:35357"
    admin_user: "admin"
    admin_password: "password"
    admin_project_name: "admin"
    admin_region_name: "RegionOne"
    domain_name: "default"
    tenant_name: "admin"

    neutron_user: "neutron"
    neutron_password: "password"
    neutron_region_name: "RegionOne"

  rabbitmq:
    address: "rabbitmq"
    admin_user: "rabbitmq"
    admin_password: "password"
    port: 5672

  ceph:
    monitors: []
    cinder_user: "cinder"
    cinder_keyring: ""
    secret_uuid: ""

  glance:
    api_url: "http://glance-api:9292"

  neutron:
    api_url: "http://neutron-server:9696"
    metadata_secret: "password"

  memcached:
    address: "memcached:11211"

nova:
  image:
    init: quay.io/stackanetes/stackanetes-kolla-toolbox:barcelona
    db_sync: quay.io/stackanetes/stackanetes-nova-api:barcelona
    api: quay.io/stackanetes/stackanetes-nova-api:barcelona
    conductor: quay.io/stackanetes/stackanetes-nova-conductor:barcelona
    scheduler: quay.io/stackanetes/stackanetes-nova-scheduler:barcelona
    novncproxy: quay.io/stackanetes/stackanetes-nova-novncproxy:barcelona
    consoleauth: quay.io/stackanetes/stackanetes-nova-consoleauth:barcelona
    compute: quay.io/stackanetes/stackanetes-nova-compute:barcelona
    libvirt: quay.io/stackanetes/stackanetes-nova-libvirt:barcelona
    post: quay.io/stackanetes/stackanetes-kolla-toolbox:barcelona
    entrypoint: quay.io/stackanetes/kubernetes-entrypoint:v0.1.0

  network:
    port:
      api: 8774
      metadata: 8775
      novncproxy: 6080

  database:
    nova_user: "nova"
    nova_password: "password"
    nova_database_name: "nova"
    nova_api_database_name: "nova_api"

  keystone:
    nova_user: "nova"
    nova_password: "password"
    nova_region_name: "RegionOne"

  ceph:
    nova_pool: "vms"

  misc:
    debug: false
    workers: 8

  dependencies:
    api:
      jobs:
      - mariadb-seed
      - keystone-db-sync
      - nova-init
      - nova-db-sync
      service:
      - mariadb
    db_sync:
      jobs:
      - nova-init
      - keystone-init
      - mariadb-seed
      service:
      - mariadb
    db_sync:
      jobs:
      - nova-init
      - keystone-init
      - mariadb-seed
      service:
      - mariadb
    post:
      jobs:
      - nova-init
      - keystone-init
      - mariadb-seed
      service:
      - mariadb
      - nova-api
    init:
      jobs:
      - mariadb-seed
      service:
      - mariadb
    compute:
      jobs:
      - nova-init
      - nova-post
      - nova-db-sync
      service:
      - keystone-api
      - nova-api
    libvirt:
      jobs:
      - nova-init
      - nova-post
      - nova-db-sync
      service:
      - keystone-api
      - nova-api
    consoleauth:
      jobs:
      - mariadb-seed
      - keystone-db-sync
      - nova-init
      - nova-db-sync
      service:
      - mariadb
    scheduler:
      jobs:
      - mariadb-seed
      - keystone-db-sync
      - nova-init
      - nova-db-sync
      service:
      - mariadb
    conductor:
      jobs:
      - mariadb-seed
      - keystone-db-sync
      - nova-init
      - nova-db-sync
      service:
      - mariadb
